### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by gregorypratt** [ben-eb/postcss-reduce-transforms#3]
Doesn't replacing items like `translate3d` with `translate` reduce performance of the animation? I thought `translate3d` invoked hardware acceleration, unless that's changed in more modern browsers?

**Comment by ben-eb** [comment]
I don't think that is the case, though I would love to see any benchmarks proving or disproving this. I'm just going off what MDN has to say in this area, which is that certain values for 3D transforms can be converted to a shorter 2D transform;

> The `rotateX()` CSS function defines a transformation that moves the element around the abscissa without deforming it. The amount of movement is defined by the specified angle; if positive, the movement will be clockwise, if negative, it will be counter-clockwise. The axis of rotation passes by the origin, defined by [the] `transform-origin` CSS property.
>
> `rotateX(a)` is a shorthand for `rotate3D(1, 0, 0, a)`.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function
